version: '3'

volumes:
  grafana:

services:
  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - 8000:3000
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/alexandrainst/alexandra-trackmap-panel/archive/refs/heads/master.zip;custom-plugin,grafana-clock-panel
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
