{
 "title": "Scorecard Dashboard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "province_id",
    "label": "Province",
    "query": "select name_km AS __text, code AS __value  from locations where parent_id is null;"
   },
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct(year) from scorecards where program_id in (${program_id})"
   },
   {
    "name": "facility_name",
    "label": "Sector",
    "query": "select name_en from facilities where parent_id is not null AND program_id in (${program_id});"
   },
   {
    "name": "facility_id",
    "label": "Sector",
    "query": "select id AS __value  from facilities where parent_id is not null AND name_en in ($facility_name) AND program_id in (${program_id});"
   },
   {
    "name": "scorecard_type",
    "label": "Scorecard Type",
    "query": "Self-Assessment : 1,Community Scorecard : 2 "
   },
   {
    "name": "age",
    "label": "Age",
    "query": "< 15 : 0 AND 14, 15 - 30 : 15 AND 30, 31 - 45 : 31 AND 45,  > 45 : 46 AND 99"
   },
   {
    "name": "gender",
    "label": "Gender",
    "query": "Male : male, Female : female, Other : other"
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": "Disability, Minority, ID Poor, Youth"
   },
   {
    "name": "program_id",
    "label": "Program",
    "query": "select name AS __text, id AS __value from programs order by id;"
   },
   {
    "name": "local_ngo_name",
    "label": "Local NGO",
    "query": "select name from local_ngos where program_id in (${program_id});"
   },
   {
    "name": "local_ngo_id",
    "label": "Local NGO",
    "query": "select id AS __value  from local_ngos where name in ($local_ngo_name) AND program_id in (${program_id});"
   }
  ]
 },
 "panels": [
  {
   "title": "ផែនទីអនុវត្តប័ណ្ណដាក់ពិន្ទុឌីជីថល",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH _submitted_scorecards AS (\n  SELECT *\n  FROM\n    (\n      SELECT\n        s.*,\n        concat_ws (\n          ', ',\n          (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n          (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n          (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n          (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n          (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n        ) as profile\n      FROM scorecards as s\n      INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n      WHERE \n        s.program_id in (${program_id})\n        AND $__timeFilter(s.conducted_date)\n        AND s.scorecard_type in ($scorecard_type)\n        AND s.year in ($year)\n        AND s.facility_id in ($facility_id)\n        AND s.local_ngo_id in ($local_ngo_id)\n        AND s.deleted_at is null\n        AND s.submitted_at is not null\n        AND p.age BETWEEN ${age:raw}\n        AND p.gender in ($gender)\n      group by s.id\n    ) as sc\n  WHERE string_to_array(sc.profile, ', ') && array[$profile]\n),\n_conducted_scorecards AS (\n  SELECT *\n  FROM _submitted_scorecards\n  WHERE completed_at is not null\n),\n_in_review_scorecards AS (\n  SELECT *\n  FROM _submitted_scorecards\n  WHERE completed_at is null\n)\n\nSELECT \n  CONCAT(\n    'អង្គការអនុវត្តប័ណ្ណដាក់ពិន្ទុ (', locations.name_km, ')', \n    '<ol>',\n    ARRAY_TO_STRING(array_agg(DISTINCT CONCAT('<li><a href=\"', local_ngos.website_url ,'\" target=\"_blank\">', local_ngos.name, '</a></li>')),''),\n    '</ol>',\n    '<p>',\n    'ការអនុវត្តប័ណ្ណដាក់ពិន្ទុ៖',\n    '<ul>',\n    '<li>គ្រោងទុក:<b> ', COUNT(*), '</b></li>',\n    '<li>កំពុងត្រួតពិនិត្យ:<b> ', (SELECT COUNT(*) FROM _in_review_scorecards WHERE province_id = locations.code), '</b></li>',\n    '<li>អនុវត្តរួចរាល់:<b> ', (SELECT COUNT(*) FROM _conducted_scorecards WHERE province_id = locations.code), '</b></li>',\n    '</ul>',\n    '</p>'\n  ) as popup,\n\n  locations.osm_latitude as latitude, \n  locations.osm_longitude as longitude,\n\n  CONCAT_WS('/', (SELECT COUNT(*) FROM _conducted_scorecards WHERE province_id = locations.code), COUNT(*)) as tooltip\n\nFROM scorecards \nINNER JOIN locations ON scorecards.province_id = locations.code\nINNER JOIN local_ngos ON scorecards.local_ngo_id = local_ngos.id\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.created_at)\n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\nGROUP BY \n  locations.name_km, locations.code, locations.latitude, locations.longitude;"
    }
   ]
  },
  {
   "title": "សង្ខេបប័ណ្ណដាក់ពិន្ទុ",
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM locations\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុសរុប (អនុវត្តរួចរាល់/កំពុងត្រួតពិនិត្យ/គ្រោងទុក)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n),\ntotal_conducted AS (\n  SELECT count(*) as \"Total Conducted\"\n  from _scorecards as sc\n  where \n    string_to_array(sc.profile, ', ') && array[$profile]\n    AND sc.completed_at is not null\n),\ntotal_planned AS (\n  SELECT\n    count(*) as \"Total Planned\"\n  FROM scorecards AS s\n  WHERE\n    s.program_id in (${program_id})\n    AND $__timeFilter(s.created_at)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n),\ntotal_in_review AS (\n  SELECT count(*) as \"Total In Review\"\n  from _scorecards as sc\n  where \n    string_to_array(sc.profile, ', ') && array[$profile]\n    AND sc.submitted_at is not null\n    AND sc.completed_at is null\n)\n\nSELECT \n  concat_ws (\n    ' / ',\n    (select * from total_conducted),\n    (select * from total_in_review),\n    (select * from total_planned)  \n  )"
    }
   ]
  },
  {
   "title": "ចំនួនប័ណ្ណដាក់ពិន្ទុដែលបានបញ្ចូលទិន្នន័យក្រោយថ្ងៃអនុវត្តជាក់ស្តែង",
   "type": "stat",
   "description": "Fomular: (Entry date - Conducted date >= 1 Day)\nឧទាហរណ៍៖ ថ្ងៃអនុវត្តប័ណ្ណដាក់ពិន្ទុជាក់ស្តែង 01-មករា-2022 តែ ថ្ងៃបញ្ចូលទិន្នន័យ 03-មករា-2022។ \n",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile,\n    EXTRACT(epoch FROM (s.finished_date - s.conducted_date))/86400 as conducted_period\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n),\ntotal_late_insert AS (\n  SELECT count(*) as \"Total Conducted\"\n  from _scorecards as sc\n  where \n    string_to_array(sc.profile, ', ') && array[$profile]\n    AND sc.completed_at is not null\n    AND conducted_period > 0\n)\n\nSELECT \n  concat_ws (\n    ' / ',\n    (select * from total_late_insert)\n  )"
    }
   ]
  },
  {
   "title": "រយៈពេលអនុវត្តប័ណ្ណដាក់ពិន្ទុ (កាលបរិច្ឆេទចាប់ផ្តើមដល់ដាក់ស្នើត្រួតពិនិត្យ)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    EXTRACT(epoch FROM (s.submitted_at - s.conducted_date))/86400 as implemented_time,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.submitted_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  group by s.id\n),\nfiltered_scorecards AS (\n  SELECT \n  (\n    CASE WHEN implemented_time <= (ceil(implemented_time) - 0.5) THEN ceil(implemented_time) - 0.5\n         ELSE ceil(implemented_time)\n    END\n  ) as duration\n  FROM _scorecards\n  WHERE string_to_array(profile, ', ') && array[$profile]\n)\n\nSELECT\n  min(duration)::integer AS \"អប្បបរមា (ថ្ងៃ)\",\n  avg(duration)::integer AS \"មធ្យម (ថ្ងៃ)\",\n  max(duration)::integer AS \"អតិបរមា (ថ្ងៃ)\"\nFROM filtered_scorecards;"
    }
   ]
  },
  {
   "title": "រយៈពេលអនុវត្តប័ណ្ណដាក់ពិន្ទុ (កាលបរិច្ឆេទដាក់ស្នើត្រួតពិនិត្យដល់អនុវត្តរួចរាល់)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    EXTRACT(epoch FROM (s.completed_at - s.submitted_at))/86400 as implemented_time,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.completed_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  group by s.id\n),\nfiltered_scorecards AS (\n  SELECT \n  (\n    CASE WHEN implemented_time <= (ceil(implemented_time) - 0.5) THEN ceil(implemented_time) - 0.5\n         ELSE ceil(implemented_time)\n    END\n  ) as duration\n  FROM _scorecards\n  WHERE string_to_array(profile, ', ') && array[$profile]\n)\n\nSELECT\n  min(duration)::integer AS \"អប្បបរមា (ថ្ងៃ)\",\n  avg(duration)::integer AS \"មធ្យម (ថ្ងៃ)\",\n  max(duration)::integer AS \"អតិបរមា (ថ្ងៃ)\"\nFROM filtered_scorecards;"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុសរុប (អនុវត្តរួចរាល់ vs គ្រោងទុក) តាមប្រភេទសេវា",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH conducted_scorecards AS (\n  SELECT *\n  FROM\n    (\n      SELECT\n        s.*,\n        concat_ws (\n          ', ',\n          (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n          (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n          (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n          (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n          (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n        ) as profile\n      FROM scorecards as s\n      INNER JOIN participants on s.id::varchar(20) = participants.scorecard_uuid\n      WHERE \n        s.program_id in (${program_id})\n        AND $__timeFilter(s.conducted_date)\n        AND s.scorecard_type in ($scorecard_type)\n        AND s.year in ($year)\n        AND s.province_id in ($province_id)\n        AND s.local_ngo_id in ($local_ngo_id)\n        AND s.deleted_at is null\n        AND s.completed_at is not null\n        AND participants.age BETWEEN ${age:raw}\n        AND participants.gender in ($gender)\n      group by s.id\n    ) as sc\n  WHERE string_to_array(sc.profile, ', ') && array[$profile]\n),\nplanned_scorecards AS (\n  SELECT\n    *\n  FROM scorecards AS s\n  WHERE\n    s.program_id in (${program_id})\n    AND $__timeFilter(s.created_at)\n    AND s.facility_id in ($facility_id) \n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n)\n\nSELECT\n  tm.name,\n  sum(tm.total_planned) as \"ចំនួនគ្រោងទុក\",\n  sum(tm.total_conducted) as \"ចំនួនអនុវត្តរួចរាល់\"\nFROM (\n  SELECT\n    facilities.name_km as name,\n    ( SELECT count(*) FROM planned_scorecards AS cs WHERE cs.facility_id = facilities.id ) as \"total_planned\",\n    ( SELECT count(*) FROM conducted_scorecards AS cs WHERE cs.facility_id = facilities.id ) as \"total_conducted\"\n  FROM planned_scorecards\n  INNER JOIN facilities ON planned_scorecards.facility_id = facilities.id\n  GROUP BY facilities.name_km, facilities.id\n) AS tm\nGROUP BY tm.name;"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុដែលអនុវត្តរួចរាល់ (វាយតម្លៃខ្លួនឯង vs ប័ណ្ណដាក់ពិន្ទុសហគមន៍) តាមប្រភេទសេវា",
   "type": "barchart",
   "description": "ប័ណ្ណដាក់ពិន្ទុដែលអនុវត្តរួចរាល់ (វាយតម្លៃខ្លួនឯង vs ប័ណ្ណដាក់ពិន្ទុសហគមន៍) តាមប្រភេទសេវា",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.completed_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n)\n\nSELECT \n  facilities.name_km as name, \n  COUNT(CASE WHEN t.scorecard_type = 1 THEN 1 END) as \"វាយតម្លៃខ្លួនឯង\",\n  COUNT(CASE WHEN t.scorecard_type = 2 THEN 2 END) as \"ប័ណ្ណដាក់ពិន្ទុសហគមន៍\"\nFROM (\n  SELECT * \n  FROM _scorecards as sc\n  WHERE string_to_array(sc.profile, ', ') && array[$profile]\n) as t\nINNER JOIN facilities ON t.facility_id = facilities.id\nGROUP BY facilities.name_km;"
    }
   ]
  },
  {
   "title": "ប័ណ្ណដាក់ពិន្ទុដែលអនុវត្តរួចរាល់តាមប្រភេទសេវា",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND s.completed_at is not null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n)\n\nSELECT \n  facilities.name_km as name, \n  COUNT(*)\nFROM (\n  SELECT * \n  FROM _scorecards\n  WHERE string_to_array(_scorecards.profile, ', ') && array[$profile]\n) as t\nINNER JOIN facilities ON t.facility_id = facilities.id\nGROUP BY facilities.name_km;"
    }
   ]
  },
  {
   "title": "ការអនុវត្តប័ណ្ណដាក់ពិន្ទុបែងចែកតាមប្រភេទឧបករណ៍",
   "type": "piechart",
   "description": "របាយការណ៍នេះរាប់បញ្ចូលតែប័ណ្ណដាក់ពិន្ទុទាំងឡាយណាដែលបានអនុវត្តរួចរាល់នៅសហគមន៍ដោយ អ្នកសម្របសម្រួលគណនេយ្យភាពសហគមន៍(CAF)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH _scorecards AS (\n  SELECT \n    s.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN s.number_of_disability > 0 THEN 'Disability' END),\n      (CASE WHEN s.number_of_ethnic_minority > 0 THEN 'Minority' END),\n      (CASE WHEN s.number_of_youth > 0 THEN 'Youth' END),\n      (CASE WHEN s.number_of_id_poor > 0 THEN 'ID Poor' END),\n      (CASE WHEN (s.number_of_disability = 0 AND s.number_of_ethnic_minority = 0 AND s.number_of_youth = 0 AND s.number_of_id_poor = 0) THEN 'N/A' END)\n    ) as profile\n  FROM scorecards as s\n  INNER JOIN participants as p on s.id::varchar(20) = p.scorecard_uuid\n  WHERE \n    s.program_id in (${program_id})\n    AND $__timeFilter(s.conducted_date)\n    AND s.scorecard_type in ($scorecard_type) \n    AND s.year in ($year) \n    AND s.facility_id in ($facility_id)\n    AND s.province_id in ($province_id)\n    AND s.local_ngo_id in ($local_ngo_id)\n    AND s.deleted_at is null\n    AND p.age BETWEEN ${age:raw}\n    AND p.gender in ($gender)\n  GROUP BY s.id\n)\n\nSELECT \n  (\n    CASE \n      WHEN sc.device_type = 'mobile' THEN 'ទូរស័ព្ទ'\n      ELSE 'ថេប្លេត'\n    END\n  ) as \"ប្រភេទឧបករណ៍\",\n  count(*)\nFROM _scorecards as sc\nWHERE string_to_array(sc.profile, ', ') && array[$profile]\nGROUP BY sc.device_type;\n"
    }
   ]
  },
  {
   "title": "អ្នកចូលរួមបែងចែកតាមភេទ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    (\n      CASE \n        WHEN gender = 'male' THEN 'ប្រុស'\n        WHEN gender = 'female' THEN 'ស្រី'\n        ELSE 'ផ្សេងៗ'\n      END\n    ) as gender_km,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n)\n\nSELECT\n  gender_km,\n  count(*)\nFROM pa\nINNER JOIN scorecards ON \n  pa.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\n  AND pa.gender in ($gender)\n  AND pa.age BETWEEN ${age:raw}\n  AND string_to_array(pa.profile, ', ') && array[$profile]\nGROUP BY gender_km\nORDER BY 1"
    }
   ]
  },
  {
   "title": "អ្នកចូលរួមបែងចែកតាមអាយុ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    (\n      CASE \n        WHEN age > 45 THEN 'អាយុ > 45'\n        WHEN age > 30 THEN 'អាយុ 31 - 45'\n        WHEN age > 14 THEN 'អាយុ 15 - 30'\n        ELSE 'អាយុ< 15'\n      END\n    ) as age_range,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n)\n\nSELECT\n  age_range,\n  count(*)\nFROM pa\nINNER JOIN scorecards ON \n  pa.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\n  AND pa.gender in ($gender)\n  AND pa.age BETWEEN ${age:raw}\n  AND string_to_array(pa.profile, ', ') && array[$profile]\nGROUP BY age_range\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "អ្នកចូលរួមបែងចែកតាមលក្ខណៈសម្បតិ្ត",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH par AS (\n  (\n    SELECT participants.*, 'ID Poor' as profile, 'ប័ណ្ណក្រីក្រ' as profile_km\n    FROM participants WHERE participants.poor_card is true\n  )\n  UNION ALL\n  (\n    SELECT participants.*, 'Disability' as profile, 'ពិការភាព' as profile_km\n    FROM participants WHERE participants.disability is true\n  )\n  UNION ALL\n  (\n    SELECT participants.*, 'Minority' as profile, 'ជនជាតិដើម' as profile_km\n    FROM participants WHERE participants.minority is true\n  )\n  UNION ALL\n  (\n    SELECT participants.*, 'Youth' as profile, 'យុវជន' as profile_km\n    FROM participants WHERE participants.youth is true\n  )\n)\n\nSELECT \n  par.profile_km, count(*)\nFROM par\nINNER JOIN scorecards ON par.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\n  AND par.gender in ($gender)\n  AND par.age BETWEEN ${age:raw}\n  AND par.profile in ($profile)\nGROUP BY par.profile_km"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យដែលស្នើឡើងច្រើនជាងគេទាំង៥",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nraised AS (\n  SELECT\n    pa.*,\n    raised_indicators.id,\n    raised_indicators.indicator_uuid\n  FROM pa\n  INNER JOIN raised_indicators ON pa.uuid = raised_indicators.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n)\n\nSELECT\n  indicators.name,\n  count(*) as \"ចំនួនស្នើឡើង\"\nFROM raised\nINNER JOIN scorecards ON\n  raised.scorecard_uuid::INTEGER = scorecards.id\nINNER JOIN indicators ON\n  raised.indicator_uuid = indicators.uuid\nWHERE \n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.year in ($year)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\nGROUP BY indicators.name\nORDER BY \"ចំនួនស្នើឡើង\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យអាទិភាព(ដែលបានអនុវត្ត)ច្រើនជាងគេទាំង៥",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nraised AS (\n  SELECT\n    pa.*,\n    raised_indicators.id,\n    raised_indicators.indicator_uuid\n  FROM pa\n  INNER JOIN raised_indicators ON pa.uuid = raised_indicators.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n    AND raised_indicators.selected is true\n)\n\nSELECT\n  indicators.name,\n  count(distinct(raised.scorecard_uuid)) as \"ចំនួនបានអនុវត្ត\"\nFROM raised\nINNER JOIN scorecards ON\n  raised.scorecard_uuid::INTEGER = scorecards.id\nINNER JOIN indicators ON\n  raised.indicator_uuid = indicators.uuid\nWHERE \n  scorecards.program_id in ($program_id)\n  AND $__timeFilter(scorecards.conducted_date)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.year in ($year)\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\nGROUP BY indicators.name\nORDER BY \"ចំនួនបានអនុវត្ត\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យអាទិភាពទាំង៥ (😁 ពេញចិត្ត)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nrate AS (\n  SELECT\n    pa.*,\n    ratings.score,\n    ratings.voting_indicator_uuid,\n    ratings.participant_uuid\n  FROM pa\n  INNER JOIN ratings ON pa.uuid = ratings.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n    AND ratings.score > 3\n)\n\nSELECT\n  indicators.name,\n  count(*) as \"ចំនួនបោះឆ្នោត\"\nFROM rate\nINNER JOIN voting_indicators\n  ON voting_indicators.uuid = rate.voting_indicator_uuid\nINNER JOIN indicators\n  ON voting_indicators.indicator_uuid = indicators.uuid\nINNER JOIN scorecards ON\n  voting_indicators.scorecard_uuid::INTEGER = scorecards.id\nWHERE\n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\nGROUP BY indicators.name\nORDER BY \"ចំនួនបោះឆ្នោត\" DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យអាទិភាពទាំង៥ (🙂 ទទួលយកបាន)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nrate AS (\n  SELECT\n    pa.*,\n    ratings.score,\n    ratings.voting_indicator_uuid,\n    ratings.participant_uuid\n  FROM pa\n  INNER JOIN ratings ON pa.uuid = ratings.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n    AND ratings.score = 3\n)\n\nSELECT\n  indicators.name,\n  count(*) as \"ចំនួនបោះឆ្នោត\"\nFROM rate\nINNER JOIN voting_indicators\n  ON voting_indicators.uuid = rate.voting_indicator_uuid\nINNER JOIN indicators\n  ON voting_indicators.indicator_uuid = indicators.uuid\nINNER JOIN scorecards ON\n  voting_indicators.scorecard_uuid::INTEGER = scorecards.id\nWHERE\n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\nGROUP BY indicators.name\nORDER BY \"ចំនួនបោះឆ្នោត\" DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "title": "លក្ខណៈវិនិច្ឆ័យអាទិភាពទាំង៥ (😡 មិនពេញចិត្ត)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "rawSql": "WITH pa AS (\n  SELECT\n    p.*,\n    concat_ws (\n      ', ',\n      (CASE WHEN p.disability = true THEN 'Disability' END),\n      (CASE WHEN p.minority = true THEN 'Minority' END),\n      (CASE WHEN p.youth = true THEN 'Youth' END),\n      (CASE WHEN p.poor_card = true THEN 'ID Poor' END),\n      (CASE WHEN (p.disability = false AND p.minority = false AND p.youth = false AND p.poor_card = false) THEN 'N/A' END)\n    ) as profile\n  FROM participants AS p\n),\nrate AS (\n  SELECT\n    pa.*,\n    ratings.score,\n    ratings.voting_indicator_uuid,\n    ratings.participant_uuid\n  FROM pa\n  INNER JOIN ratings ON pa.uuid = ratings.participant_uuid\n  WHERE\n    string_to_array(pa.profile, ', ') && array[$profile]\n    AND pa.gender in ($gender)\n    AND pa.age BETWEEN ${age:raw}\n    AND ratings.score < 3\n)\n\nSELECT\n  indicators.name,\n  count(*) as \"ចំនួនបោះឆ្នោត\"\nFROM rate\nINNER JOIN voting_indicators\n  ON voting_indicators.uuid = rate.voting_indicator_uuid\nINNER JOIN indicators\n  ON voting_indicators.indicator_uuid = indicators.uuid\nINNER JOIN scorecards ON\n  voting_indicators.scorecard_uuid::INTEGER = scorecards.id\nWHERE\n  scorecards.program_id in (${program_id})\n  AND $__timeFilter(scorecards.conducted_date)  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\n  AND scorecards.local_ngo_id in ($local_ngo_id)\n  AND scorecards.deleted_at is null\n  AND scorecards.completed_at is not null\nGROUP BY indicators.name\nORDER BY \"ចំនួនបោះឆ្នោត\" DESC\nLIMIT 5;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "options": {
    "content": "<div style=\"display: flex;\">\n<div style=\"display: flex;margin: 0 auto;\">\n<div style=\"text-align: center; margin-right: 20px\">\n<h5 style=\"font-size: 14px;\">គាំទ្រមូលនិធិដោយ/Funded by</h5>\n<img src=\"https://digital-csc.org/assets/eu-3902d24e7e972494ede15c7dc533bc20589ef6e80aca3335518cea5944984c09.png\"  width=\"70\"/>\n</div>\n\n<div style=\"text-align: center; margin-top: 0\">\n<h5 style=\"font-size: 14px;\">អនុវត្តដោយ/Implemented by</h5>\n<div style=\"margin-top: 24px\">\n<img src=\"https://digital-csc.org/assets/care_logo-30bc7807ccb532ee750d35b55a3e94c40e688a88a18d0497c4e244bc56f4017d.png\" width=\"130\" height=\"40\" />\n<img src=\"https://digital-csc.org/assets/api-a84a9246854e6e9c471aa6982fb90ed27377b050f69318966fe0c3923d371886.png\"  width=\"55\" style=\"margin: 0 20px;\"/>\n<img src=\"https://digital-csc.org/assets/instedd-ilabsea-252db350ccbce84ff56c4057db2f6a5761873c8d7b4c9c5ee9c31049ba7d3792.png\"  width=\"180\" style=\"margin-top: 5px;\"/>\n</div>\n</div>\n\n</div>\n</div>\n  \n<div style=\"text-align: center;\">\n  <a href=\"https://digital-csc.org/\" target=\"_blank\" >អំពីយើង/About Us</a>\n</div>\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM locations\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  }
 ]
}