{
 "title": "Scorecard Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "province_id",
    "label": "Province",
    "query": "select name_km AS __text, code AS __value  from locations where parent_id is null;"
   },
   {
    "name": "year",
    "label": "Year",
    "query": "select distinct(year) from scorecards"
   },
   {
    "name": "facility_id",
    "label": "Sector",
    "query": "select name_en AS __text, id AS __value  from facilities where parent_id is not null AND program_id=1;"
   },
   {
    "name": "scorecard_type",
    "label": "Scorecard Type",
    "query": "Self-Assessment : 1,Community Scorecard : 2 "
   }
  ]
 },
 "panels": [
  {
   "title": "Scorecard Implemented Map",
   "type": "alexandra-trackmap-panel",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  CONCAT(\n    'អង្គការអនុវត្តប័ណ្ណដាក់ពិន្ទុ (', locations.name_km, ')', \n    '<ol>',\n    ARRAY_TO_STRING(array_agg(DISTINCT CONCAT('<li><a href=\"#\" target=\"_blank\">', local_ngos.name, '</a></li>')),''),\n    '</ol>'\n  ) as popup,\n  locations.latitude, \n  locations.longitude,\n  CONCAT(\n    COUNT(CASE WHEN scorecards.locked_at IS NOT null THEN 1 END), \n    '/', \n    count(*)\n  ) as tooltip\nFROM scorecards \nINNER join locations ON scorecards.province_id = locations.code\nINNER join local_ngos ON scorecards.local_ngo_id = local_ngos.id\nWHERE \n  scorecards.program_id=1\n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\nGROUP BY \n  locations.name_km, locations.latitude, locations.longitude;"
    }
   ]
  },
  {
   "title": "Total Scorecard Conducted",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n  facilities.name_en as name, \n  COUNT(CASE WHEN scorecards.scorecard_type = 1 THEN 1 END) as self_assessment,\n  COUNT(CASE WHEN scorecards.scorecard_type = 2 THEN 2 END) as community_scorecard\nFROM scorecards INNER JOIN facilities ON scorecards.facility_id = facilities.id\nWHERE \n scorecards.program_id=1  \n AND scorecards.scorecard_type in ($scorecard_type) \n AND scorecards.year in ($year) \n AND scorecards.facility_id in ($facility_id)\n AND scorecards.province_id in ($province_id)\nGROUP BY facilities.name_en;\n"
    }
   ]
  },
  {
   "title": "By Gender",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  gender AS \"gender\",\n  count(*)\nFROM participants\ninner join scorecards on participants.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id = 1\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\nGROUP BY gender\nORDER BY 1"
    }
   ]
  },
  {
   "title": "By Citizen Profile",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(*) AS \"ID Poor\"\nFROM participants\ninner join scorecards on participants.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id = 1\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND participants.poor_card is true\nORDER BY 1\n"
    },
    {
     "rawSql": "SELECT\n  count(*) AS \"Disability\"\nFROM participants\ninner join scorecards on participants.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id = 1\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND participants.disability is true\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(*) AS \"Minority\"\nFROM participants\ninner join scorecards on participants.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id = 1\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND participants.minority is true\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  count(*) AS \"Youth\"\nFROM participants\ninner join scorecards on participants.scorecard_uuid = scorecards.id::varchar(255)\nWHERE \n  scorecards.program_id = 1\n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.year in ($year)\n  AND scorecards.scorecard_type in ($scorecard_type)\n  AND scorecards.province_id in ($province_id)\n  AND participants.youth is true\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Top 5 indicator",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "rawSql": "(SELECT\n  indicators.name,\n  count(*) as total_raised\nFROM raised_indicators\n  INNER JOIN scorecards ON\n    raised_indicators.scorecard_uuid::INTEGER = scorecards.id\n  JOIN indicators ON \n    raised_indicators.indicatorable_id = indicators.id\n    AND raised_indicators.indicatorable_type = 'Indicator'\nWHERE \n  scorecards.program_id=1  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\nGROUP BY indicators.name)\n\nUNION\n\n(SELECT\n  custom_indicators.name,\n  count(*) as total_raised\nFROM raised_indicators\n  INNER JOIN scorecards ON\n    raised_indicators.scorecard_uuid::INTEGER = scorecards.id\n  JOIN custom_indicators ON \n    raised_indicators.indicatorable_id = custom_indicators.id\n    AND raised_indicators.indicatorable_type = 'CustomIndicator'\nWHERE \n  scorecards.program_id=1  \n  AND scorecards.scorecard_type in ($scorecard_type) \n  AND scorecards.year in ($year) \n  AND scorecards.facility_id in ($facility_id)\n  AND scorecards.province_id in ($province_id)\nGROUP BY custom_indicators.name)\nORDER BY total_raised DESC\nLIMIT 5;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "options": {
    "content": "<div style=\"display: flex\">\n<div style=\"text-align: center; margin-right: 20px\">\n<h5 style=\"font-size: 14px;\">គាំទ្រមូលនិធិដោយ/Funded by</h5>\n<img src=\"https://digital-csc.org/assets/eu-3902d24e7e972494ede15c7dc533bc20589ef6e80aca3335518cea5944984c09.png\"  width=\"70\"/>\n</div>\n\n<div style=\"text-align: center\">\n<h5 style=\"font-size: 14px;\">អនុវត្តដោយ/Implemented by</h5>\n<div style=\"display: flex; align-items: center; justify-content: center; margin-top: 30px;\">\n<img src=\"https://digital-csc.org/assets/care_logo-30bc7807ccb532ee750d35b55a3e94c40e688a88a18d0497c4e244bc56f4017d.png\" width=\"110\" height=\"35px\" />\n<img src=\"https://digital-csc.org/assets/api-a84a9246854e6e9c471aa6982fb90ed27377b050f69318966fe0c3923d371886.png\"  width=\"40\" height: \"30px\" style=\"margin: 0 10px;\"/>\n<img src=\"https://digital-csc.org/assets/instedd-ilabsea-252db350ccbce84ff56c4057db2f6a5761873c8d7b4c9c5ee9c31049ba7d3792.png\"  width=\"180\"/>\n</div>\n</div>\n</div>\n\n<div style=\"text-align:center; margin-top: 20px;\">\n<a href=\"https://digital-csc.org/\" target=\"_blank\" >About Us</a>\n</div>\n  "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  latitude\nFROM locations\nWHERE\n  $__timeFilter(created_at)\nORDER BY 1"
    }
   ]
  }
 ]
}